// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Demo(Props) {
  return React.createElement("div", {
              className: "bg-blue-200 min-h-screen flex items-center justify-center text-4xl"
            }, "Hello Rescript-React with TailWind CSS!");
}

var make = Demo;

export {
  make ,
  
}
/* react Not a pure module */
